// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3yVnEpr-e94BOb9aOWoaGgTnfajyIAqg',
    appId: '1:412312221607:web:1f15a09b5bd68185fe2882',
    messagingSenderId: '412312221607',
    projectId: 'bash-smart-home-esp32',
    authDomain: 'bash-smart-home-esp32.firebaseapp.com',
    databaseURL: 'https://bash-smart-home-esp32-default-rtdb.firebaseio.com',
    storageBucket: 'bash-smart-home-esp32.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa4IkDxl34lOyPqidU_G0JRqucgTZbmek',
    appId: '1:412312221607:android:cbe1bbaa166192c0fe2882',
    messagingSenderId: '412312221607',
    projectId: 'bash-smart-home-esp32',
    databaseURL: 'https://bash-smart-home-esp32-default-rtdb.firebaseio.com',
    storageBucket: 'bash-smart-home-esp32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFemswlO22BvI_XiuxzhzqaLgvbBiHgHY',
    appId: '1:412312221607:ios:651177a91771440cfe2882',
    messagingSenderId: '412312221607',
    projectId: 'bash-smart-home-esp32',
    databaseURL: 'https://bash-smart-home-esp32-default-rtdb.firebaseio.com',
    storageBucket: 'bash-smart-home-esp32.firebasestorage.app',
    iosBundleId: 'com.example.smartHomeFrontEnd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFemswlO22BvI_XiuxzhzqaLgvbBiHgHY',
    appId: '1:412312221607:ios:651177a91771440cfe2882',
    messagingSenderId: '412312221607',
    projectId: 'bash-smart-home-esp32',
    databaseURL: 'https://bash-smart-home-esp32-default-rtdb.firebaseio.com',
    storageBucket: 'bash-smart-home-esp32.firebasestorage.app',
    iosBundleId: 'com.example.smartHomeFrontEnd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3yVnEpr-e94BOb9aOWoaGgTnfajyIAqg',
    appId: '1:412312221607:web:20bd7f386ad93e75fe2882',
    messagingSenderId: '412312221607',
    projectId: 'bash-smart-home-esp32',
    authDomain: 'bash-smart-home-esp32.firebaseapp.com',
    databaseURL: 'https://bash-smart-home-esp32-default-rtdb.firebaseio.com',
    storageBucket: 'bash-smart-home-esp32.firebasestorage.app',
  );
}
